"""
Product Search Tool (Playwright-based)
========================================
Searches the site's product search endpoint using a real headless browser
(Playwright) and reports whether a product (by name or item/SKU number)
exists.

Why a headless browser, not plain requests: this site sits behind Akamai
Bot Manager, which requires a real browser to execute a JavaScript
challenge before granting access. Plain HTTP requests get a 403 regardless
of headers, because the site is actually checking for cryptographic
sensor cookies (_abck, bm_sz, bm_so, etc.) that only get generated by
running Akamai's JS -- and those cookies are short-lived and tied to the
session that generated them, so copy-pasting them from a browser/Postman
only works until they expire. Playwright launches a real (headless)
Chromium browser, so that challenge resolves fresh on every run.

The site itself is a server-rendered Next.js app: once past Akamai, the
full search result (result count, product titles, prices) is embedded as
structured JSON in a <script id="__NEXT_DATA__"> tag -- we extract and
parse that directly rather than scraping visible text.
"""
from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from urllib.parse import urljoin, quote_plus

from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError

logger = logging.getLogger(__name__)

DEFAULT_TIMEOUT_MS = 20000  # page navigation timeout
POST_LOAD_WAIT_MS = 1500    # extra settle time for Akamai's JS challenge

_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
)

_NEXT_DATA_RE = re.compile(
    r'<script id="__NEXT_DATA__" type="application/json">(.*?)</script>',
    re.S,
)


@dataclass
class ProductSearchResult:
    query: str
    search_url: str
    found: bool
    result_count: int
    message: str
    products: list[dict] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "query": self.query,
            "search_url": self.search_url,
            "found": self.found,
            "result_count": self.result_count,
            "message": self.message,
            "products": self.products,
        }


def search_product(
    base_url: str,
    query: str,
    store_id: str,
    search_path_template: str = "/en/search?search-bar={query}&storeId={store_id}",
    timeout_ms: int = DEFAULT_TIMEOUT_MS,
) -> ProductSearchResult:
    """
    Search for *query* (a product name or item/SKU number) using a real
    headless browser and report whether it exists.

    Args:
        base_url: Site root, e.g. "https://www.realcanadiansuperstore.ca"
        query: Product name or item number to search for.
        store_id: Store location ID (required by this site's search URL).
        search_path_template: Path template with {query}/{store_id} placeholders.
        timeout_ms: Page navigation timeout, in milliseconds.
    """
    search_path = search_path_template.format(
        query=quote_plus(query), store_id=store_id
    )
    search_url = urljoin(base_url, search_path)

    try:
        html = _fetch_rendered_html(search_url, timeout_ms)
    except PlaywrightTimeoutError as exc:
        logger.error("Playwright navigation timed out: %s", exc)
        return ProductSearchResult(
            query=query, search_url=search_url, found=False, result_count=0,
            message=f"Page load timed out: {exc}",
        )
    except Exception as exc:  # noqa: BLE001
        logger.error("Playwright fetch failed: %s", exc)
        return ProductSearchResult(
            query=query, search_url=search_url, found=False, result_count=0,
            message=f"Browser fetch failed: {exc}",
        )

    match = _NEXT_DATA_RE.search(html)
    if not match:
        return ProductSearchResult(
            query=query, search_url=search_url, found=False, result_count=0,
            message=(
                "Could not find __NEXT_DATA__ on the rendered page -- "
                "may still be blocked, or the page structure changed."
            ),
        )

    try:
        data = json.loads(match.group(1))
        search_data = data["props"]["pageProps"]["initialSearchData"]
        result_count = int(search_data.get("searchResultsCount", 0))
    except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        logger.error("Failed to parse __NEXT_DATA__: %s", exc)
        return ProductSearchResult(
            query=query, search_url=search_url, found=False, result_count=0,
            message=f"Failed to parse search data: {exc}",
        )

    products = _extract_product_tiles(search_data)

    return ProductSearchResult(
        query=query,
        search_url=search_url,
        found=result_count > 0,
        result_count=result_count,
        message=(
            f"Found {result_count} matching product(s)."
            if result_count > 0
            else "No products found for this search."
        ),
        products=products,
    )


def _fetch_rendered_html(url: str, timeout_ms: int) -> str:
    """Launch a headless browser, navigate to *url*, and return the rendered HTML."""
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        try:
            context = browser.new_context(
                user_agent=_USER_AGENT,
                locale="en-CA",
                viewport={"width": 1280, "height": 800},
            )
            page = context.new_page()
            page.goto(url, timeout=timeout_ms, wait_until="networkidle")
            # Akamai's JS challenge can take a moment to fully resolve even
            # after networkidle; give it a bit more time before reading.
            page.wait_for_timeout(POST_LOAD_WAIT_MS)
            return page.content()
        finally:
            browser.close()


def _extract_product_tiles(search_data: dict) -> list[dict]:
    """Pull basic product info (title, brand, price) out of the search JSON."""
    products: list[dict] = []
    try:
        components = search_data["layout"]["sections"]["mainContentCollection"]["components"]
    except (KeyError, TypeError):
        return products

    for component in components:
        if component.get("componentId") != "productGridComponent":
            continue
        for tile in component.get("data", {}).get("productTiles", []):
            products.append(
                {
                    "product_id": tile.get("productId"),
                    "title": tile.get("title"),
                    "brand": tile.get("brand"),
                    "price": tile.get("pricing", {}).get("displayPrice"),
                    "link": tile.get("link"),
                }
            )
    return products